"""empty message

Revision ID: 0aeedea1dd46
Revises: c428a5b48c95
Create Date: 2022-01-12 17:34:25.013298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aeedea1dd46'
down_revision = 'c428a5b48c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
