"""empty message

Revision ID: 60e08091d5ea
Revises: 0aeedea1dd46
Create Date: 2022-01-12 17:38:58.469747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e08091d5ea'
down_revision = '0aeedea1dd46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('bla', sa.String(), nullable=False))
    op.add_column('users', sa.Column('bla2', sa.String(), nullable=False))
    op.add_column('votes', sa.Column('bla3', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'bla3')
    op.drop_column('users', 'bla2')
    op.drop_column('posts', 'bla')
    # ### end Alembic commands ###
